language: java
jdk:
  - openjdk8

branches:
  only:
    -master

install:
  - git clone https://github.com/kimjunghak/webservice.git

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - kboy1025@gmail.com